baitap/baitap/urls.py
from django.contrib import admin
from django.urls import path
from selection import views
from django.conf.urls import include, url
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^', include(('selection.urls', 'selection'), namespace='selection')),
    url(r'^guest/', include('guest.urls', namespace='guest')),
    path('', views.start, name='start'),
    path('hms/', views.home, name='register'),
    path('reg_form/', views.register, name='reg_form'),
    path('login/', views.user_login, name='login'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('warden_login/', views.warden_login, name='warden_login'),
    path('warden_login/leave', views.leave_admin, name='leave_admin'),
    path('warden_login/student_leaves/<int:std_id>/', views.student_leaves, name='student_leaves'),
    path('warden_login/leave_confirm/<int:lv_id>/', views.leave_confirm, name='leave_confirm'),
    path('warden_login/leave_reject/<int:lv_id>/', views.leave_reject, name='leave_reject'),
    path('warden_login/empty/', views.empty_rooms, name='empty_rooms'),
    path('warden_login/present_leaves/', views.present_leaves, name='present_leaves'),
    path('warden_login/mess_rebate/', views.mess_rebate, name='mess_rebate'),
    path('warden_login/guest_requests/', views.guest_requests, name='guest_requests'),
    path('warden_login/bookings/<int:b_id>/', views.bookings, name='bookings'),
    path('warden_login/confirm/<int:res_id>/', views.guest_accept, name='guest_accept'),
    path('warden_login/cancel/<int:res_id>/', views.guest_reject, name='guest_reject'),
    path('warden_profile/', views.warden_profile, name='warden_profile'),
    path('warden_dues/', views.warden_dues, name='warden_dues'),
    path('warden_add_due/', views.warden_add_due, name='warden_add_due'),
    path('warden_remove_due/', views.warden_remove_due, name='warden_remove_due'),
    path('hostels/', views.hostels, name='hostel_all'),
    path('hostels/<slug:hostel_name>/', views.hostel_detail_view, name='hostel'),
    path('login/edit/', views.edit, name='edit'),
    path('login/select/', views.select, name='select'),
    path('login/repair/', views.repair, name='repair'),
    path('logout/', views.logout_view, name='logout'),
    path('reg_form/login/edit/', views.edit, name='update'),
    path('BH5_GroundFloor/', views.BH5_GroundFloor, name='BH5_GroundFloor'),
    path('BH5_Floor1/', views.BH5_Floor1, name='BH5_Floor1'),
    path('BH5_Floor2/', views.BH5_Floor2, name='BH5_Floor2'),
    path('BH5_Floor3/', views.BH5_Floor3, name='BH5_Floor3'),
    path('BH5_Floor4/', views.BH5_Floor4, name='BH5_Floor4'),
    path('BH5_Floor5/', views.BH5_Floor5, name='BH5_Floor5'),
    path('BH5_Floor6/', views.BH5_Floor6, name='BH5_Floor6'),
    path('login/leave', views.user_leave, name='leave_status'),
]

baitap/guest/urls.py
from django.contrib import admin
from django.urls import path
from . import views as guest_view
from django.conf.urls import include, url

app_name = 'guest'
urlpatterns = [
    path('', guest_view.start, name='start'),
    path('register/', guest_view.register, name='register'),
    path('login/', guest_view.user_login, name='login'),
    path(r'login/home/', guest_view.home, name='home'),
    path(r'login/select/<int:res_id>/', guest_view.select, name='select'),
    # url(r'profile/^$', guest_view.profile, name='profile'),
    path(r'login/edit/<int:res_id>/', guest_view.edit, name='edit'),
    path(r'login/confirm/<int:res_id>/', guest_view.confirm, name='confirm'),
    path(r'login/cancel/<int:res_id>/', guest_view.cancel, name='cancel'),
    path(r'login/pdf/<int:res_id>/', guest_view.generate_pdf, name='pdf'),
    path(r'login/bookings/', guest_view.bookings, name='bookings'),
    path('logout/', guest_view.logout_view, name='logout'),
]

baitap/selection/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [

]

baitap/selection/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django import forms
from django.core.exceptions import ValidationError
import datetime

YEARS= [x for x in range(2020,2022)]

class UserForm(UserCreationForm):
    password1 = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {
            'username': 'same as your roll no.',
        }

   

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = [
            'student_name',
            'father_name',
            'enrollment_no',
            'course',
            'dob',
            'gender']


class SelectionForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['room']


class DuesForm(forms.Form):
    choice = forms.ModelChoiceField(queryset=Student.objects.all().filter(no_dues=True))


class NoDuesForm(forms.Form):
    choice = forms.ModelChoiceField(queryset=Student.objects.all().filter(no_dues=False))


class DateInput(forms.DateInput):
    input_type = 'date'


class LeaveForm(forms.ModelForm):
    start_date = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget(years=YEARS))
    end_date = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget(years=YEARS))
    reason = forms.CharField(max_length=100, help_text='100 characters max.',
                             widget=forms.TextInput(attrs={'placeholder': 'Enter Reason here'}))
    class Meta:
        model = Leave
        fields = [
            'start_date',
            'end_date',
            'reason']
class RepairForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['repair']


class RebateForm(forms.Form):
    rebate = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget(years=YEARS))

baitap/selection/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.http import HttpResponse, Http404
from selection.models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime,calendar
from guest.models  import Room as Guest_Room,Reservation,Guest
from django.core.exceptions import ObjectDoesNotExist


def home(request):
    return render(request, 'home.html')


def start(request):
    return render(request, 'start.html')


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        # error1, error2 = False, False
        print(form.is_valid())
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()
            Student.objects.create(user=new_user)
            cd = form.cleaned_data
            print(str(cd))
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password1'])
            if user is not None:
                if user.is_active:

                    login(request, user)
                    return redirect('login/edit/')
                else:

                    return HttpResponse('Disabled account')
            else:

                return HttpResponse('Invalid Login')
        else:
            form = UserForm()
            args = {'form': form}
            return render(request, 'reg_form.html', args)
        # elif len(form.data['password1']) <= 8 or len(form.data['password2']) <= 8:
        #     if len(form.data['password1']) <= 8:
        #         error1 = True
        #     if len(form.data['password2']) <= 8:
        #         error2 = True
        #     return render(request, 'reg_form.html', {'form': form, 'error1': error1, 'error2': error2})

    else:

        form = UserForm()
        args = {'form': form}
        return render(request, 'reg_form.html', args)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_warden:
                    return HttpResponse('Invalid Login')
                if user.is_active:
                    login(request, user)
                    # student = request.user.student
                    # leaves = Leave.objects.filter(student=request.user.student)
                    # return render(request, 'profile.html', {'student': student, 'leaves': leaves})
                    return redirect('../student_profile/')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


def warden_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'])
            print(cd['username'],cd['password'])
            print(user)
            if user is not None:
                if not user.is_warden:
                    return HttpResponse('Invalid Login')
                elif user.is_active:
                    login(request, user)
                    # print('True')
                    # room_list = request.user.warden.hostel.room_set.all()
                    # context = {'rooms': room_list}
                    # return render(request, 'warden.html', context)
                    return redirect('../warden_profile/')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


def warden_profile(request):
    user = request.user
    if user is not None:
        if not user.is_warden:
            return HttpResponse('Invalid Login')
        elif user.is_active:
            login(request, user)
            print('True')
            room_list = request.user.warden.hostel.room_set.all().order_by('no')
            context = {'rooms': room_list}
            return render(request, 'warden.html', context)
        else:
            return HttpResponse('Disabled account')
    else:
        return HttpResponse('Invalid Login')


def student_profile(request):
    user = request.user
    if user is not None:
        if user.is_warden:
            return HttpResponse('Invalid Login')
        if user.is_active:
            login(request, user)
            student = request.user.student
            leaves = Leave.objects.filter(student=request.user.student)
            return render(request, 'profile.html', {'student': student, 'leaves': leaves})
        else:
            return HttpResponse('Disabled account')
    else:
        return HttpResponse('Invalid Login')



@login_required
def edit(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, instance=request.user.student)
        if form.is_valid():
            form.save()
            student = request.user.student
            leaves = Leave.objects.filter(student=request.user.student)
            return render(request, 'profile.html', {'student': student, 'leaves': leaves})
        else:
            form = RegistrationForm()
            return render(request, 'edit.html', {'form': form})
    else:
        form = RegistrationForm(instance=request.user.student)
        return render(request, 'edit.html', {'form': form})


@login_required
def select(request):

    if request.method == 'POST':
        if request.user.student.room:
            room_id_old = request.user.student.room_id

        if not request.user.student.no_dues:
            return HttpResponse('You have dues. Please contact your Hostel Caretaker or Warden')
        form = SelectionForm(request.POST, instance=request.user.student)
        if form.is_valid():
            if request.user.student.room_id:
                # stud = form.save(commit=False)
                # print(request.user.student.room_id, stud.room_id)
                request.user.student.room_allotted = True
                r_id_after = request.user.student.room_id
                room = Room.objects.get(id=r_id_after)
                room.vacant = False
                room.save()
                try:
                    room = Room.objects.get(id=room_id_old)
                    room.vacant = True
                    room.save()
                except BaseException:
                    pass
            else:
                request.user.student.room_allotted = False
                try:
                    room = Room.objects.get(id=room_id_old)
                    room.vacant = True
                    room.save()
                except BaseException:
                    pass
            student  = form.save()
            print(student.room_id)
            student = request.user.student
            leaves = Leave.objects.filter(student=request.user.student)
            return render(request, 'profile.html', {'student': student, 'leaves': leaves})
    else:
        if not request.user.student.no_dues:
            return HttpResponse('You have dues. Please contact your Hostel Caretaker or Warden')
        form = SelectionForm(instance=request.user.student)
        student_gender = request.user.student.gender
        student_course = request.user.student.course
        if student_course is None:
            return HttpResponse('No Course Selected <br> '
                                '<h3><a href = \'..\edit\' style = "text-align: center; color: Red ;"> Update Profile </a> </h3> ')
        student_room_type = request.user.student.course.room_type
        hostel = Hostel.objects.filter(
            gender=student_gender, course=student_course).order_by('name')
        print(student_gender, student_course, student_room_type)
        print(hostel)
        x = Room.objects.none()
        if student_room_type == 'B':
            # print(student_room_type)
            # for i in range(len(hostel)):
            #     h_id = hostel[i].id
            x = Room.objects.filter(
                hostel__id=hostel, room_type=['S','D'], vacant=True).order_by('no')

            # x = x | a
        else:
            # for i in range(len(hostel)):
            #     h_id = hostel[i].id
            x = Room.objects.filter(
                hostel_id__in=hostel, room_type=student_room_type, vacant=True).order_by('hostel_id','no')
            print(x)
            # x = x | a
        form.fields["room"].queryset = x
        print('x',x)
        return render(request, 'select_room.html', {'form': form})


def repair(request):

    if request.method == 'POST':
        form = RepairForm(request.POST)
        if form.is_valid() & request.user.student.room_allotted:

            rep = form.cleaned_data['repair']
            room = request.user.student.room
            room.repair = rep
            room.save()
            return HttpResponse('<h3>Complaint Registered</h3> <br> <a href = \'../../student_profile\''
                                ' style = "text-align: center; color: Red ;"> Go Back to Profile </a>')
        elif not request.user.student.room_allotted:
            return HttpResponse('<h3>First Select a Room </h3> <br> <a href = \'../select\''
                                ' style = "text-align: center; color: Red ;"> SELECT ROOM </a> ')

        else:
            form = RepairForm()
            room = request.user.student.room
            return render(request, 'repair_form.html', {'form': form, 'room': room})

baitap/selection/templates/add_due.html
{% extends 'base.html' %}

{% block content %}
<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields">{{ form.as_p }}</div>
      <input class="button-custom" type="submit" value="ADD DUE">
    </form>
  </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'warden_dues' %}">
        Dues
    </a>
    <!--<a href="{% url 'warden_add_due' %}">-->
        <!--Add Due-->
    <!--</a>-->
    <a href="{% url 'warden_remove_due' %}">
        Remove Due
    </a>
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

baitap/selection/templates/base.html
<html>

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    
       {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'selection/style.css' %}">
</head>

<body>

<div class="nav">
    <div class="nav-header">
        <div class="nav-title">
            <a href="{% url 'register' %}">Hostel Management System</a>
        </div>
    </div>
  
    <div class="nav-btn">
        <label for="nav-check">
            <span></span>
            <span></span>
            <span></span>
        </label>
    </div>
    <input type="checkbox" id="nav-check">
    <div class="nav-links">
        {% block more_links %}
        {% endblock more_links %}


    </div>


</div>
<div >
    {% block content %}
    {% endblock content %}

</div>

<footer>
  <div class="copyright" align="center" >
    2021 © Hostel System Management
  </div>
</footer>


</body>
</html>

baitap/selection/templates/bookings.html
{% extends 'base.html' %}


{% block content %}



{% if bookings.count == 0 %}
<center><h4 class = 's_book' style="padding: 30px;
    text-align: center; color: red ;"> No Bookings Done!!</h4></center>
{% else %}
<center> <h3 class = 's_book' style="padding: 30px;
    text-align: center; color: red ;"> ALL Successful Bookings of {{guest.first_name}}  {{guest.last_name}} ({{guest.user.username}})</h3></center>

 <div class="wrapper" style="
    padding-top: 0px;">

        <div class="table">

            <div class="row header">
                <div class="cell">
                    ID
                </div>
                <div class="cell">
                    Room No
                </div>
                <div class="cell">
                    CheckIn
                </div>
                <div class="cell">
                    CheckOut
                </div>
                <div class="cell">
                    Status
                </div>

            </div>
            {% for booking in bookings %}
                <div class="row">
                    <div class="cell" data-title="Number">
                        {{forloop.counter}}
                    </div>
                    <div class="cell" data-title="Number">
                        {{booking.room.no}}
                    </div>
                    <div class="cell" data-title="Date">
                         {{booking.checkIn}}
                    </div>
                    <div class="cell" data-title="Date">
                        {{booking.checkOut}}
                    </div>
                    <div class="cell" style="{% if booking.accept %} color: green {% elif booking.reject %} color:Red {% endif %}" data-title="status">

                        {% if booking.accept %}
                        Accepted
                        {% elif booking.reject %}
                        Rejected
                        {% else %}
                        Pending
                        {% endif %}

                    </div>



                </div>
            {% endfor %}
        </div>

    </div>
 <br>
{% endif %}

{% endblock content %}




{% block more_links %}
      <a href="{% url 'leave_admin' %}">
        Leave requests
    </a>
    <a href="{% url 'empty_rooms' %}">
        Empty Rooms
    </a>
    <a href="{% url 'present_leaves' %}">
        Present Leave
    </a>
    <a href="{% url 'mess_rebate' %}">
        Mess Rebate
    </a>
    <a href="{% url 'guest_requests' %}">
        Guest Room Requests
    </a>
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

baitap/selection/templates/dues.html
{% extends 'base.html' %}

{% block content %}

    <div class="wrapper">

        {% for student in students %}
            {% if not student.no_dues %}
                <div class="table">

                    <div class="row">
                        <div class="cell">
                            Student Name
                        </div>
                        <div class="cell">
                            {{ student.student_name }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="cell">
                            Enrollment Number
                        </div>
                        <div class="cell">
                            {{ student.enrollment_no }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="cell">
                            Course
                        </div>
                        <div class="cell">
                            {{ student.course }}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <a class="button-custom" href="{% url 'warden_add_due' %}">
        Add a due
    </a>
    </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'empty_rooms' %}">
        Empty Rooms
    </a>
    <!--<a href="{% url 'warden_dues' %}">-->
        <!--Dues-->
    <!--</a>-->
    <a href="{% url 'warden_add_due' %}">
        Add Due
    </a>
    <a href="{% url 'warden_remove_due' %}">
        Remove Due
    </a>
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

baitap/selection/templates/hostels_all.html
{% extends 'base.html' %}

{% block content %}

<div class="wrap">
    {% for hostel in hostels %}
    <a class="button-custom" href="{% url 'hostel' hostel.name %}">
        Hostel - {{hostel.name}}
    </a>
    {% endfor %}

  </div>

{% endblock content %}


{% block more_links %}
    <!--<a href="{% url 'login' %}">Login</a>-->
    <!--<a href="{% url 'reg_form' %}">Register</a>-->
    <!--<a href="{% url 'guest:start' %}">Guest Room Booking</a>-->
    <a href="{% url 'register' %}">Hostel Management System</a>
    <a href="{% url 'guest:start' %}">Guest Room Booking</a>
{% endblock more_links %}

baitap/selection/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="wrap">
	
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields"> Username <br><br> {{ form.username }}</div>
      <div class="fields"> Password <br><br> {{ form.password }}</div>
      <input class="button-custom" type="submit" value="LOGIN">
    </form>
  </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'reg_form' %}">Register</a>
{% endblock more_links %}

baitap/selection/templates/pending.html
{% extends 'base.html' %}

{% block content %}
    {% if not leaves %}
    <h2 style = "text-align: center; color: red ;">No Pending Requests</h2>
    {% else %}
    <h2 style = "text-align: center; color: red ;">Pending Requests</h2>
    <div class="wrapper">

        <div class="table">

            <div class="row header">
                <div class="cell">
                    Student Name
                </div>
                <div class="cell">
                    Room No (Hostel)
                </div>
                <div class="cell">
                    Start Date
                </div>
                <div class="cell">
                    End Date
                </div>
                <div class="cell">
                    Reason
                </div>
                <div class="cell">
                    Accept
                </div>
                <div class="cell">
                    Reject
                </div>
            </div>
            {% for leave in leaves %}
                <div class="row">
                    <div class="cell" data-title="Name">
                        <a  href="{% url 'student_leaves' leave.student.id %}"> {{ leave.student.student_name }} </a>
                    </div>
                    <div class="cell" data-title="Name">
                        {{ leave.student.room.no }} in {{ leave.student.room.hostel.name}}
                    </div>
                    <div class="cell" data-title="Date">
                        {{ leave.start_date }}
                    </div>
                    <div class="cell" data-title="Date">
                        {{ leave.end_date }}
                    </div>
                    <div class="cell" data-title="Name">
                        {{ leave.reason }}
                    </div>
                    <div class="cell">
                    <a class="btn btn-success" href="{% url 'leave_confirm' leave.id %}"> Grant  </a>
                    </div>
                    <div class="cell">
                    <a class="btn btn-danger" href="{% url 'leave_reject' leave.id %}"> Reject  </a>
                    </div>


                </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    <br><br>


    {% if accepted %}
    <h2 style = "text-align: center; color: blue ;" > Accepted Leave Requests</h2>

    <div class="wrapper">
        <div class="table">

            <div class="row header">
                <div class="cell">
                    Student Name
                </div>
                <div class="cell">
                    Enrollment No
                </div>
                <div class="cell">
                    Course
                </div>
                <div class="cell">
                    Start Date
                </div>
                <div class="cell">
                    End Date
                </div>
                <div class="cell">
                    Reason
                </div>

            </div>
            {% for leave in accepted %}
                <div class="row">
                    <div class="cell">
                        <a  href="{% url 'student_leaves' leave.student.id %}"> {{leave.student.student_name}} </a>
                    </div>
                    <div class="cell">
                        {{leave.student.enrollment_no}}
                    </div>
                     <div class="cell">
                        {{leave.student.course.code}}
                    </div>

                    <div class="cell">
                        {{leave.start_date}}
                    </div>
                    <div class="cell">
                        {{leave.end_date}}
                    </div>
                    <div class="cell">
                        {{leave.reason}}
                    </div>


                 </div>
            {% endfor %}



        </div>

    </div>
    {% endif %}

{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'empty_rooms' %}">
        Empty Rooms
    </a>
    <a href="{% url 'present_leaves' %}">
        Present Leave
    </a>
    <a href="{% url 'mess_rebate' %}">
        Mess Rebate
    </a>
     <a href="{% url 'guest_requests' %}">
        Guest Room Requests
    </a>
    <!--<a href="{% url 'warden_dues' %}">-->
        <!--Dues-->
    <!--</a>-->
    <!--<a href="{% url 'warden_add_due' %}">-->
        <!--Add Due-->
    <!--</a>-->
    <!--<a href="{% url 'warden_remove_due' %}">-->
        <!--Remove Due-->
    <!--</a>-->
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

baitap/selection/templates/present_leaves.html
{% extends 'base.html' %}

{% block content %}
    {% if not student %}
    <h2 style = "text-align: center; color: red ;">No Student on Leave</h2>
    {% else %}
    <h2 style = "text-align: center; color: red ;">Students on Leave</h2>
    <div class="wrapper">

        <div class="table">

            <div class="row header">

                <div class="cell">
                    Student Name
                </div>
                <div class="cell">
                    Enrollment No
                </div>
                <div class="cell">
                    Course
                </div>
                <div class="cell">
                    Gender
                </div>

            </div>
            {% for stud in student %}
                <div class="row">

                    <div class="cell">

                            {{ stud.student_name }}

                    </div>
                     <div class="cell">

                            {{ stud.enrollment_no }}

                    </div>
                    <div class="cell">

                            {{ stud.course.code }}

                    </div>
                    <div class="cell">

                            {{ stud.gender }}

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
      {% endif %}
{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'leave_admin' %}">
        Leave requests
    </a>
    <a href="{% url 'empty_rooms' %}">
        Empty Rooms
    </a>
    <a href="{% url 'mess_rebate' %}">
        List of Student on Leave
    </a>
     <a href="{% url 'guest_requests' %}">
        Guest Room Requests
    </a>
    <!--<a href="{% url 'warden_dues' %}">-->
        <!--Dues-->
    <!--</a>-->
    <!--<a href="{% url 'warden_add_due' %}">-->
        <!--Add Due-->
    <!--</a>-->
    <!--<a href="{% url 'warden_remove_due' %}">-->
        <!--Remove Due-->
    <!--</a>-->
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

baitap/selection/templates/reg_form.html
{% extends 'base.html' %}

{% block content %}
<div class="wrap" style="background-color: green;">

    <form  method="post" >
        {% csrf_token %}
      <div class="fields"> Username <br><br> {{ form.username }}</div>


      <div class="fields"> Password <br><br>
           <div class = 'error1' >
             {% if error1 %}
        <p style="color: red;">
            Please enter password of atleast 8 characters or more.
        </p>
        {% endif %}
        </div>
          {{ form.password1 }}
      </div>



      <div class="fields"> Repeat Password <br><br>
          <div class="error2">
            {% if error2 %}
        <p style="color: red;">
            Please enter confirm password (same as password)
        </p>
        {% endif %}
              </div>
          {{ form.password2 }} </div>

      <input class="button-custom" type="submit" value="REGISTER">
    </form>
  </div>
{% endblock content %}